baseURL = 'http://foxyseta.github.io/visimp-pages'
languageCode = 'en-us'
theme = "hugo-book"
title = 'Visimp'

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'algol'
    tabWidth = 2


[params]
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
  BookTheme = 'auto'
  BookRepo = 'https://github.com/foxyseta/visimp-pages'
