baseURL = 'http://visimp.github.io/pages'
languageCode = 'en-us'
theme = "hugo-book"
title = 'visimp'

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'algol'
    tabWidth = 2

[menu]
[[menu.after]]
  name = "Project Repository"
  url = "https://github.com/visimp/visimp"
  weight = 10

[[menu.after]]
  name = "Website repository"
  url = "https://github.com/visimp/pages"
  weight = 20

[params]
  BookCommitPath = 'commit'
  # BookEditPath = 'edit/main/' # one content/ folder too many
  BookTheme = 'auto'
  BookRepo = 'https://github.com/visimp/visimp'
